/*
 * HouseGate Directory service worker (generated by DirectoryServiceWorkerController).
 * Scope is /directory only, so the Scanner, Registry, Audit Trail and every POST stay online-only.
 */
const VERSION = @json($version);
const STATIC_CACHE = 'hg-dir-static-' + VERSION;   // CSS, fonts, icons: rebuilt whenever one of those files changes
const PAGE_CACHE = 'hg-dir-pages';                 // the Directory HTML (the layout also clears it on logout)
const PHOTO_CACHE = 'hg-dir-photos';               // survives deploys; each photo is keyed by its ?v= URL
const DIR_PATH = @json($dirPath);
const PHOTO_PREFIX = @json($photoPrefix);
const ASSETS = @json($assets);
const ASSET_PATHS = new Set(ASSETS);
const SHELL_TIMEOUT_MS = 4000;                     // slow connection: answer from cache after this long

// Plain person silhouette, same colours as the Directory's own "no photo" tile.
const PLACEHOLDER = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 50"><rect width="40" height="50" fill="#f1f5f9"/>'
    + '<circle cx="20" cy="19" r="7" fill="#cbd5e1"/><path d="M6 50c0-11 6-17 14-17s14 6 14 17z" fill="#cbd5e1"/></svg>';

self.addEventListener('install', event => {
    event.waitUntil((async () => {
        const cache = await caches.open(STATIC_CACHE);
        // 'reload' skips the HTTP cache so a deploy never precaches an old file. One failure fails the install.
        await cache.addAll(ASSETS.map(u => new Request(u, { cache: 'reload' })));
        await cacheShell();   // best effort, so even the very first visit works offline afterwards
        await self.skipWaiting();
    })());
});

self.addEventListener('activate', event => {
    event.waitUntil((async () => {
        for (const name of await caches.keys()) {
            if (name.startsWith('hg-dir-static-') && name !== STATIC_CACHE) await caches.delete(name);
        }
        await self.clients.claim();
    })());
});

self.addEventListener('fetch', event => {
    const request = event.request;
    if (request.method !== 'GET') return;   // saves, deactivations, logins: always straight to the network
    const url = new URL(request.url);
    if (url.origin !== self.location.origin) return;

    if (request.mode === 'navigate' && url.pathname === DIR_PATH) event.respondWith(shell(event));
    else if (ASSET_PATHS.has(url.pathname)) event.respondWith(staticAsset(request));
    else if (url.pathname.startsWith(PHOTO_PREFIX)) event.respondWith(photo(event));
    // anything else (including /directory/roster, which Phase 8 handles itself) is left alone
});

async function cacheShell() {
    try {
        // 'manual': a redirect to the login page must never be stored as the Directory
        const res = await fetch(DIR_PATH, { credentials: 'same-origin', redirect: 'manual' });
        if (res.status === 200 && res.type === 'basic') await (await caches.open(PAGE_CACHE)).put(DIR_PATH, res);
    } catch (e) { /* offline during install: the first online visit stores it instead */ }
}

// Directory page: network first (fresh page, fresh CSRF token), cache when offline, failing or slow.
async function shell(event) {
    const pages = await caches.open(PAGE_CACHE);
    const cached = await pages.match(DIR_PATH);
    const clean = new URL(event.request.url).search === '';   // a ?q= render has its filters prefilled, so it is not kept

    let stored = Promise.resolve();
    const network = fetch(event.request).then(res => {
        if (clean && res.status === 200 && res.type === 'basic') stored = pages.put(DIR_PATH, res.clone()).catch(() => {});
        return res;
    });
    event.waitUntil(network.then(() => stored, () => {}));   // keep refreshing the cache even after answering from it

    if (!cached) return network;
    const timer = new Promise(resolve => setTimeout(resolve, SHELL_TIMEOUT_MS, null));
    const fresh = await Promise.race([network.catch(() => null), timer]);
    return fresh && fresh.status < 500 ? fresh : cached;
}

// CSS / fonts / icons: cache first. ?v= is ignored because VERSION already changes with the files.
async function staticAsset(request) {
    const hit = await caches.match(request, { cacheName: STATIC_CACHE, ignoreSearch: true });
    return hit || fetch(request);
}

// Photos: cache as they are viewed. A replaced photo has a new ?v=, so it is a new entry and the old one is dropped.
async function photo(event) {
    const cache = await caches.open(PHOTO_CACHE);
    const hit = await cache.match(event.request);
    if (hit) return hit;
    try {
        const res = await fetch(event.request);
        if (res.status === 200 && res.type === 'basic') event.waitUntil(storePhoto(cache, event.request, res.clone()));
        return res;
    } catch (e) {
        // Offline and never viewed before: a neutral tile instead of a broken image. Not cached.
        return new Response(PLACEHOLDER, { headers: { 'Content-Type': 'image/svg+xml', 'Cache-Control': 'no-store' } });
    }
}

async function storePhoto(cache, request, response) {
    await cache.put(request, response);
    const now = new URL(request.url);
    for (const key of await cache.keys()) {
        const old = new URL(key.url);
        if (old.pathname === now.pathname && old.search !== now.search) await cache.delete(key);
    }
}